version: 2
sources:
  - name: niyyah_tracks
    database: niyyah tracks MVP
    schema: public
    tables: 
      - name: donor
      - name: charity
      - name: project
      - name: testimonials
      - name: donation 